from pathlib import Path

ROOT = Path("legacy/fu-v02-reconnect-preview")
INTEGRATION = ROOT / "fu_reconnect_integration.py"
APP = ROOT / "flash_sync_v02.py"
TEST = ROOT / "test_fu_reconnect_integration.py"

source = INTEGRATION.read_text(encoding="utf-8")
anchor = '''    def revoke_entries(\n'''
helper = '''    def disable_features(self, entry_ids) -> int:\n        """Atomically turn manor/fishing off for the supplied launch entries.\n\n        Crop, quantity and fishing profile selections are intentionally retained\n        so the user can re-enable individual roles later without rebuilding them.\n        """\n        wanted = []\n        seen = set()\n        for raw in entry_ids:\n            entry_id = str(raw or "").strip()\n            if entry_id and entry_id not in seen:\n                seen.add(entry_id)\n                wanted.append(entry_id)\n        if not wanted:\n            return 0\n\n        with self._lock:\n            previous = {str(key): dict(value) for key, value in self.settings.items()}\n            changed = []\n            for entry_id in wanted:\n                row = self.setting(entry_id)\n                if bool(row.get("manor_enabled", False)) or bool(row.get("fishing_enabled", False)):\n                    row["manor_enabled"] = False\n                    row["fishing_enabled"] = False\n                    changed.append(entry_id)\n            if not changed:\n                return 0\n            try:\n                self._save_settings()\n            except Exception:\n                self.settings = previous\n                raise\n            manor_pairs = [\n                self.manors.get(entry_id) for entry_id in changed\n                if self.manors.get(entry_id) is not None\n            ]\n            live = []\n            for entry_id in changed:\n                record = self.records.get(entry_id)\n                worker = self.workers.get(record.hwnd) if record else None\n                if record is not None and worker is not None and worker.is_alive():\n                    live.append((entry_id, record, worker))\n\n        for pair in manor_pairs:\n            manager, _lifetime_stop = pair\n            try:\n                manager.cancel_current()\n            except Exception:\n                LOG.exception("failed to cancel manor during batch disable")\n\n        for entry_id, record, worker in live:\n            try:\n                current = self.binding_loader(entry_id).get(record.hwnd)\n                if current is not None:\n                    worker.apply_binding(current, announce=False)\n            except Exception:\n                LOG.exception("failed to apply batch-disabled automation settings")\n        return len(changed)\n\n'''
if source.count(anchor) != 1:
    raise SystemExit(f"batch-disable integration anchor count={source.count(anchor)}")
source = source.replace(anchor, helper + anchor, 1)
INTEGRATION.write_text(source, encoding="utf-8", newline="\n")

app = APP.read_text(encoding="utf-8")
old = '''        ttk.Button(automation_edit, text="儲存莊園／釣魚", command=self.save_automation_selected).pack(side="left")\n'''
new = '''        ttk.Button(automation_edit, text="儲存莊園／釣魚", command=self.save_automation_selected).pack(side="left")\n        ttk.Button(\n            automation_edit, text="本組全部關閉", command=self.disable_all_automation_for_current_group,\n        ).pack(side="left", padx=(8, 0))\n'''
if app.count(old) != 1:
    raise SystemExit(f"batch-disable button anchor count={app.count(old)}")
app = app.replace(old, new, 1)

anchor = '''    def switch_group(self) -> None:\n'''
helper = '''    def disable_all_automation_for_current_group(self) -> None:\n        entries = tuple(self.current_group().launch_entries)\n        entry_ids = tuple(str(entry.entry_id or "").strip() for entry in entries)\n        entry_ids = tuple(entry_id for entry_id in entry_ids if entry_id)\n        if not entry_ids:\n            self.write_log("本組沒有可關閉的莊園／釣魚角色。")\n            return\n        try:\n            changed = int(self.automation.disable_features(entry_ids))\n        except Exception as exc:\n            self.write_log(f"本組莊園／釣魚全部關閉失敗：{exc}")\n            messagebox.showwarning(\n                "自動重連", "本組莊園／釣魚未能完整關閉；原設定保持不變。"\n            )\n            return\n        self.automation_manor_enabled.set(False)\n        self.automation_fishing_enabled.set(False)\n        selected_id = self.automation_selected_entry_id\n        if selected_id and selected_id in entry_ids:\n            self.load_automation_editor(selected_id)\n        self.refresh_automation_rows()\n        if changed:\n            self.write_log(\n                f"本組已一次關閉 {changed} 個角色的莊園／釣魚；作物、數量與魚級設定保留。"\n            )\n        else:\n            self.write_log("本組莊園／釣魚原本已全部關閉。")\n\n'''
if app.count(anchor) != 1:
    raise SystemExit(f"batch-disable UI method anchor count={app.count(anchor)}")
app = app.replace(anchor, helper + anchor, 1)
APP.write_text(app, encoding="utf-8", newline="\n")

test = TEST.read_text(encoding="utf-8")
anchor = '''class StrictRegistryTests(unittest.TestCase):\n'''
case = '''class BatchAutomationDisableTests(unittest.TestCase):\n    @staticmethod\n    def controller(settings):\n        ctl = object.__new__(EmbeddedAutomationController)\n        ctl._lock = threading.RLock()\n        ctl.settings = {str(key): dict(value) for key, value in settings.items()}\n        ctl.manors = {}\n        ctl.records = {}\n        ctl.workers = {}\n        ctl._save_settings = mock.Mock()\n        return ctl\n\n    def test_batch_disable_is_atomic_and_preserves_choices(self):\n        ctl = self.controller({\n            "a": {\n                "manor_enabled": True, "manor_crop_key": "rare_tree",\n                "manor_quantity": 7, "fishing_enabled": True,\n                "fishing_profile_id": "fish-5",\n            },\n            "b": {\n                "manor_enabled": False, "manor_crop_key": "normal_rock",\n                "manor_quantity": 16, "fishing_enabled": True,\n                "fishing_profile_id": "fish-7",\n            },\n        })\n        changed = ctl.disable_features(("a", "b", "a"))\n        self.assertEqual(changed, 2)\n        ctl._save_settings.assert_called_once_with()\n        self.assertFalse(ctl.settings["a"]["manor_enabled"])\n        self.assertFalse(ctl.settings["a"]["fishing_enabled"])\n        self.assertEqual(ctl.settings["a"]["manor_crop_key"], "rare_tree")\n        self.assertEqual(ctl.settings["a"]["manor_quantity"], 7)\n        self.assertEqual(ctl.settings["a"]["fishing_profile_id"], "fish-5")\n        self.assertFalse(ctl.settings["b"]["manor_enabled"])\n        self.assertFalse(ctl.settings["b"]["fishing_enabled"])\n        self.assertEqual(ctl.settings["b"]["fishing_profile_id"], "fish-7")\n\n    def test_batch_disable_rolls_back_every_role_on_save_failure(self):\n        original = {\n            "a": {"manor_enabled": True, "fishing_enabled": True},\n            "b": {"manor_enabled": True, "fishing_enabled": False},\n        }\n        ctl = self.controller(original)\n        ctl._save_settings.side_effect = OSError("disk blocked")\n        with self.assertRaises(OSError):\n            ctl.disable_features(("a", "b"))\n        self.assertEqual(ctl.settings, original)\n\n    def test_ui_exposes_current_group_all_off_button(self):\n        source = (Path(__file__).parent / "flash_sync_v02.py").read_text(encoding="utf-8")\n        self.assertIn('text="本組全部關閉"', source)\n        self.assertIn('command=self.disable_all_automation_for_current_group', source)\n        self.assertIn('self.automation.disable_features(entry_ids)', source)\n        self.assertIn('作物、數量與魚級設定保留', source)\n\n\n'''
if test.count(anchor) != 1:
    raise SystemExit(f"batch-disable test anchor count={test.count(anchor)}")
test = test.replace(anchor, case + anchor, 1)
TEST.write_text(test, encoding="utf-8", newline="\n")

print("LIVE_FIX_APPLIED current-group manor/fishing all-off control")
