from pathlib import Path

ROOT = Path('legacy/fu-v02-reconnect-preview')
APP = ROOT / 'flash_sync_v02.py'
TEST = ROOT / 'test_fu_reconnect_integration.py'

app = APP.read_text(encoding='utf-8')
old = '''def find_existing_fu_instance_path() -> str:\n    current_pid = os.getpid()\n    paths: list[str] = []\n\n    def callback(hwnd, _lparam):\n        try:\n            hwnd_value = int(hwnd)\n            if get_window_process_id(hwnd_value) == current_pid:\n                return True\n            title = get_window_title(hwnd_value).strip()\n            if not title.startswith(APP_DISPLAY_NAME):\n                return True\n            path = get_window_process_path(hwnd_value).strip()\n            if not path:\n                return True\n            filename = os.path.basename(path)\n            if APP_DISPLAY_NAME not in filename:\n                return True\n            paths.append(path)\n        except Exception:\n            pass\n        return True\n\n    try:\n        user32.EnumWindows(EnumWindowsProc(callback), 0)\n    except Exception:\n        return ''\n    return paths[0] if paths else ''\n'''
new = '''def find_existing_fu_instance_path() -> str:\n    current_pid = os.getpid()\n    matches: list[tuple[int, str]] = []\n\n    def callback(hwnd, _lparam):\n        try:\n            hwnd_value = int(hwnd)\n            pid = get_window_process_id(hwnd_value)\n            if not pid or pid == current_pid:\n                return True\n            title = get_window_title(hwnd_value).strip()\n            # This is the app's actual Tk root title contract.  Do not require\n            # QueryFullProcessImageNameW to succeed: a legacy one-file build can\n            # expose its Tk window while the executable path lookup is unavailable\n            # during extraction/parent-child handoff.\n            if title != APP_DISPLAY_NAME and not title.startswith(APP_DISPLAY_NAME + " - "):\n                return True\n            path = get_window_process_path(hwnd_value).strip()\n            matches.append((hwnd_value, path))\n        except Exception:\n            pass\n        return True\n\n    try:\n        user32.EnumWindows(EnumWindowsProc(callback), 0)\n    except Exception:\n        return ''\n    if not matches:\n        return ''\n    # A non-empty sentinel still blocks a legacy instance even when Windows does\n    # not expose its process path. notify_existing_instance can then use a generic\n    # cross-version warning instead of allowing a second application UI.\n    return matches[0][1] or '<existing-fu-instance>'\n'''
if app.count(old) != 1:
    raise SystemExit(f'v18 legacy-window helper anchor count={app.count(old)}')
app = app.replace(old, new, 1)

old_notify = '''    if existing_path:\n        try:\n            current_path = os.path.abspath(sys.executable)\n            if os.path.normcase(os.path.abspath(existing_path)) != os.path.normcase(current_path):\n                message_box = user32.MessageBoxW\n                message_box.argtypes = [\n                    wintypes.HWND, wintypes.LPCWSTR, wintypes.LPCWSTR, wintypes.UINT\n                ]\n                message_box.restype = ctypes.c_int\n                message_box(\n                    None,\n                    '偵測到另一個版本的輔魔仍在執行。\\n\\n'\n                    f'目前執行：{os.path.basename(existing_path)}\\n'\n                    f'你剛啟動：{os.path.basename(current_path)}\\n\\n'\n                    '為避免不同版本同時控制同一批 Flash，本次不啟動第二份；'\n                    '已把目前執行中的輔魔叫回前景。\\n'\n                    '若你正在換新版，請先用目前輔魔的齒輪選單「關閉輔魔」，再開新版。',\n                    '輔魔版本切換',\n                    0x00000030 | 0x00010000,\n                )\n        except Exception:\n            pass\n'''
new_notify = '''    if existing_path:\n        try:\n            current_path = os.path.abspath(sys.executable)\n            known_existing_path = existing_path != '<existing-fu-instance>'\n            different_path = (\n                not known_existing_path\n                or os.path.normcase(os.path.abspath(existing_path))\n                != os.path.normcase(current_path)\n            )\n            if different_path:\n                message_box = user32.MessageBoxW\n                message_box.argtypes = [\n                    wintypes.HWND, wintypes.LPCWSTR, wintypes.LPCWSTR, wintypes.UINT\n                ]\n                message_box.restype = ctypes.c_int\n                running_name = (\n                    os.path.basename(existing_path)\n                    if known_existing_path\n                    else '既有輔魔'\n                )\n                message_box(\n                    None,\n                    '偵測到另一個版本的輔魔仍在執行。\\n\\n'\n                    f'目前執行：{running_name}\\n'\n                    f'你剛啟動：{os.path.basename(current_path)}\\n\\n'\n                    '為避免不同版本同時控制同一批 Flash，本次不啟動第二份；'\n                    '已把目前執行中的輔魔叫回前景。\\n'\n                    '若你正在換新版，請先用目前輔魔的齒輪選單「關閉輔魔」，再開新版。',\n                    '輔魔版本切換',\n                    0x00000030 | 0x00010000,\n                )\n        except Exception:\n            pass\n'''
if app.count(old_notify) != 1:
    raise SystemExit(f'v18 notify anchor count={app.count(old_notify)}')
app = app.replace(old_notify, new_notify, 1)
APP.write_text(app, encoding='utf-8', newline='\n')

text = TEST.read_text(encoding='utf-8')
anchor = '''class ExistingWindowReattachTests(unittest.TestCase):\n'''
case = '''class SingleInstanceLegacyWindowRegressionTests(unittest.TestCase):\n    def test_legacy_guard_uses_main_window_title_not_process_path(self):\n        source = Path(__file__).with_name("flash_sync_v02.py").read_text(encoding="utf-8")\n        helper = source.split("def find_existing_fu_instance_path() -> str:", 1)[1].split("def notify_existing_instance()", 1)[0]\n        self.assertIn('title != APP_DISPLAY_NAME', helper)\n        self.assertIn('title.startswith(APP_DISPLAY_NAME + " - ")', helper)\n        self.assertIn("matches.append((hwnd_value, path))", helper)\n        self.assertIn("or '<existing-fu-instance>'", helper)\n        self.assertNotIn("if not path:", helper)\n        self.assertNotIn("APP_DISPLAY_NAME not in filename", helper)\n\n    def test_legacy_guard_still_does_not_touch_product_ui(self):\n        source = Path(__file__).with_name("flash_sync_v02.py").read_text(encoding="utf-8")\n        self.assertNotIn("        self.create_clock_bar()\\n", source)\n        self.assertIn("self.create_floating_status_window()", source)\n        self.assertIn("QuickCodeFloatingControl(", source)\n\n\n'''
if text.count(anchor) != 1:
    raise SystemExit(f'v18 regression anchor count={text.count(anchor)}')
text = text.replace(anchor, case + anchor, 1)
TEST.write_text(text, encoding='utf-8', newline='\n')

print('LIVE_FIX_V18_APPLIED legacy single-instance detection no longer depends on process-path lookup')
